# App: Customer CRUD Application
# Package: postgres
# File: Dockerfile.postgres
# Version: 2.0.34
# Author: Bobwares
# Date: 2025-06-05 00:14:14 UTC
# Description: Dockerfile to run PostgreSQL for development.
#
FROM postgres:15
ENV POSTGRES_DB=customerdb
ENV POSTGRES_USER=customer
ENV POSTGRES_PASSWORD=password
EXPOSE 5432
