# App: Customer CRUD Application
# Package: customer-api
# File: e2e/create-customer.http
# Version: 2.0.37
# Author: Bobwares
# Date: 2025-06-05 02:43:30 UTC
# Description: E2E test for creating a customer.
#
POST http://localhost:3001/customers
Content-Type: application/json

{
  "first": "Alice",
  "last": "Smith",
  "age": 30,
  "email": "alice.smith@example.com",
  "address": {
    "street": "123 Main",
    "city": "Anytown",
    "state": "CA",
    "zipcode": "12345"
  }
}
