# App: Customer CRUD Application
# Package: customer-api
# File: e2e/get-customer.http
# Version: 2.0.36
# Author: Bobwares
# Date: 2025-06-05 01:49:22 UTC
# Description: E2E test for retrieving a single customer.
#
GET http://localhost:3001/customers/1
