# App: Customer CRUD Application
# Package: customer-api
# File: e2e/list-customers.http
# Version: 2.0.37
# Author: Bobwares
# Date: 2025-06-05 02:43:30 UTC
# Description: E2E test for retrieving all customers.
#
GET http://localhost:3001/customers
