# App: Customer CRUD Application
# Package: customer-api
# File: e2e/update-customer.http
# Version: 2.0.31
# Author: Bobwares
# Date: 2025-06-04 21:50:39 UTC
# Description: E2E test for updating a customer.
#
PATCH http://localhost:3001/customers/1
Content-Type: application/json

{
  "name": "Alice Updated"
}
